from typing import TypedDict, List

# Task is user input 
# Plan by planner agent 
# Generated by generator Agent
# Documents by Researcher Agent & Reviewer Agent
# Amount of tries throughout workflow 
# Limit of tries 
class AgentState(TypedDict):
    task: str
    plan: str
    generated: str
    content: List[str]
    revision_number: int
    max_revisions: int