from typing import TypedDict, List

# Task is user input 
# Plan by planner agent 
# Generated by Generator Agent
# Documents by Researcher Agent 
# Grading score by Grader Agent
# Final review by Reviewer Agent
# Hellucination score by Reviewer Agent
# Search number by Researcher Agent
# Max searches by Researcher Agent
# Amount of generations throughout workflow 
# Limit

class AgentState(TypedDict):
    task: str
    plan: str
    generated: str
    content: List[str]
    grading_score: int
    final_review: str
    hellucination_score: int
    search_number: int
    max_searches: int
    revision_number: int
    max_revisions: int